version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inversionesji
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL_1: jdbc:postgresql://db-monolito:5432/InversionesJI
      SPRING_DATASOURCE_USERNAME_1: postgres
      SPRING_DATASOURCE_PASSWORD_1: admin
      SPRING_DATASOURCE_URL_2: jdbc:postgresql://db-propiedad:5432/PropiedadService
      SPRING_DATASOURCE_USERNAME_2: postgres
      SPRING_DATASOURCE_PASSWORD_2: admin
    depends_on:
      - db-monolito
      - db-propiedad
    networks:
      - my-network

  db-monolito:
    image: postgres:latest
    environment:
      POSTGRES_DB: InversionesJI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - my-network

  db-propiedad:
    image: postgres:latest
    environment:
      POSTGRES_DB: PropiedadService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - my-network

networks:
  my-network:
    external: true
